"""revision_number_three

Revision ID: 99f7b5a3ec07
Revises: 44fa5ad9b043
Create Date: 2024-05-14 08:42:50.085397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99f7b5a3ec07'
down_revision: Union[str, None] = '44fa5ad9b043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urldata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('urltable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urltable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='urltable_pkey')
    )
    op.drop_table('urldata')
    # ### end Alembic commands ###
