FROM node:20-alpine

RUN npm install -g npm@10.8.0
RUN npm install -g create-react-app@5.0.1

WORKDIR /app


# docker build -t react_builder .
# docker run -it --rm -v "$PWD":/app:rw react_builder npx create-react-app my_react_app